/**
 * Administrative divisions of the Republic of Uzbekistan.
 *
 * 12 viloyat + the Republic of Karakalpakstan + the city of Tashkent, subdivided into
 * districts (tuman) and district-level cities (shahar). Region coordinates are the
 * administrative centres.
 *
 * Provenance: the national administrative-territorial classifier (SOATO/MHOBT). District
 * boundaries do change — new districts are periodically created and renamed — so this file
 * is versioned and the seeder is idempotent: re-running it inserts what is missing and
 * updates names in place, without disturbing markets already attached to a district.
 *
 * District `center` is intentionally omitted where no authoritative coordinate is on hand.
 * Markets carry their own precise location, which is what proximity search uses.
 */

export interface SeedDistrict {
  code: string;
  uz: string;
  ru: string;
  en: string;
  isCity?: boolean;
  center?: { lat: number; lng: number };
}

export interface SeedRegion {
  code: string;
  uz: string;
  uzCyrl: string;
  ru: string;
  en: string;
  center: { lat: number; lng: number };
  districts: SeedDistrict[];
}

export const SEED_REGIONS: SeedRegion[] = [
  {
    code: 'QRQ',
    uz: "Qoraqalpogʻiston Respublikasi",
    uzCyrl: 'Қорақалпоғистон Республикаси',
    ru: 'Республика Каракалпакстан',
    en: 'Republic of Karakalpakstan',
    center: { lat: 42.4531, lng: 59.6103 },
    districts: [
      { code: 'QRQ-NUK-C', uz: 'Nukus shahri', ru: 'город Нукус', en: 'Nukus city', isCity: true, center: { lat: 42.4531, lng: 59.6103 } },
      { code: 'QRQ-AMU', uz: 'Amudaryo tumani', ru: 'Амударьинский район', en: 'Amudaryo District' },
      { code: 'QRQ-BER', uz: 'Beruniy tumani', ru: 'Берунийский район', en: 'Beruniy District' },
      { code: 'QRQ-BOZ', uz: "Boʻzatov tumani", ru: 'Бозатауский район', en: 'Bozatov District' },
      { code: 'QRQ-CHI', uz: 'Chimboy tumani', ru: 'Чимбайский район', en: 'Chimboy District' },
      { code: 'QRQ-ELL', uz: "Ellikqalʼa tumani", ru: 'Элликкалинский район', en: 'Ellikqala District' },
      { code: 'QRQ-KEG', uz: 'Kegeyli tumani', ru: 'Кегейлийский район', en: 'Kegeyli District' },
      { code: 'QRQ-MOY', uz: "Moʻynoq tumani", ru: 'Муйнакский район', en: 'Moynaq District' },
      { code: 'QRQ-NUK', uz: 'Nukus tumani', ru: 'Нукусский район', en: 'Nukus District' },
      { code: 'QRQ-QAN', uz: "Qanlikoʻl tumani", ru: 'Канлыкульский район', en: 'Qanlikol District' },
      { code: 'QRQ-QON', uz: "Qoʻngʻirot tumani", ru: 'Кунградский район', en: 'Qongirot District' },
      { code: 'QRQ-QOR', uz: "Qoraoʻzak tumani", ru: 'Караузякский район', en: 'Qorao\u02bbzak District' },
      { code: 'QRQ-SHU', uz: 'Shumanay tumani', ru: 'Шуманайский район', en: 'Shumanay District' },
      { code: 'QRQ-TAX', uz: "Taxtakoʻpir tumani", ru: 'Тахтакупырский район', en: 'Taxtakopir District' },
      { code: 'QRQ-TAK', uz: 'Taxiatosh tumani', ru: 'Тахиаташский район', en: 'Taxiatosh District' },
      { code: 'QRQ-TOR', uz: "Toʻrtkoʻl tumani", ru: 'Турткульский район', en: 'Tortkol District' },
      { code: 'QRQ-XOJ', uz: 'Xoʻjayli tumani', ru: 'Ходжейлийский район', en: 'Xojayli District' },
    ],
  },
  {
    code: 'AND',
    uz: 'Andijon viloyati',
    uzCyrl: 'Андижон вилояти',
    ru: 'Андижанская область',
    en: 'Andijan Region',
    center: { lat: 40.7821, lng: 72.3442 },
    districts: [
      { code: 'AND-AND-C', uz: 'Andijon shahri', ru: 'город Андижан', en: 'Andijan city', isCity: true, center: { lat: 40.7821, lng: 72.3442 } },
      { code: 'AND-XON-C', uz: 'Xonobod shahri', ru: 'город Ханабад', en: 'Xonobod city', isCity: true },
      { code: 'AND-AND', uz: 'Andijon tumani', ru: 'Андижанский район', en: 'Andijan District' },
      { code: 'AND-ASA', uz: 'Asaka tumani', ru: 'Асакинский район', en: 'Asaka District' },
      { code: 'AND-BAL', uz: 'Baliqchi tumani', ru: 'Балыкчинский район', en: 'Baliqchi District' },
      { code: 'AND-BOZ', uz: "Boʻston tumani", ru: 'Бустанский район', en: 'Boston District' },
      { code: 'AND-BUL', uz: 'Buloqboshi tumani', ru: 'Булакбашинский район', en: 'Buloqboshi District' },
      { code: 'AND-IZB', uz: 'Izboskan tumani', ru: 'Избасканский район', en: 'Izboskan District' },
      { code: 'AND-JAL', uz: 'Jalaquduq tumani', ru: 'Джалакудукский район', en: 'Jalaquduq District' },
      { code: 'AND-MAR', uz: 'Marhamat tumani', ru: 'Мархаматский район', en: 'Marhamat District' },
      { code: 'AND-OLT', uz: "Oltinkoʻl tumani", ru: 'Алтынкульский район', en: 'Oltinkol District' },
      { code: 'AND-PAX', uz: 'Paxtaobod tumani', ru: 'Пахтаабадский район', en: 'Paxtaobod District' },
      { code: 'AND-QOR', uz: "Qoʻrgʻontepa tumani", ru: 'Кургантепинский район', en: 'Qo\u02bbrg\u02bbontepa District' },
      { code: 'AND-SHA', uz: 'Shahrixon tumani', ru: 'Шахриханский район', en: 'Shahrixon District' },
      { code: 'AND-ULU', uz: "Ulugʻnor tumani", ru: 'Улугнорский район', en: 'Ulug\u02bbnor District' },
      { code: 'AND-XOJ', uz: 'Xoʻjaobod tumani', ru: 'Ходжаабадский район', en: 'Xojaobod District' },
    ],
  },
  {
    code: 'BUX',
    uz: 'Buxoro viloyati',
    uzCyrl: 'Бухоро вилояти',
    ru: 'Бухарская область',
    en: 'Bukhara Region',
    center: { lat: 39.7681, lng: 64.4556 },
    districts: [
      { code: 'BUX-BUX-C', uz: 'Buxoro shahri', ru: 'город Бухара', en: 'Bukhara city', isCity: true, center: { lat: 39.7681, lng: 64.4556 } },
      { code: 'BUX-KOG-C', uz: 'Kogon shahri', ru: 'город Каган', en: 'Kogon city', isCity: true },
      { code: 'BUX-BUX', uz: 'Buxoro tumani', ru: 'Бухарский район', en: 'Bukhara District' },
      { code: 'BUX-GIJ', uz: "Gʻijduvon tumani", ru: 'Гиждуванский район', en: 'G\u02bbijduvon District' },
      { code: 'BUX-JON', uz: 'Jondor tumani', ru: 'Жондорский район', en: 'Jondor District' },
      { code: 'BUX-KOG', uz: 'Kogon tumani', ru: 'Каганский район', en: 'Kogon District' },
      { code: 'BUX-OLO', uz: 'Olot tumani', ru: 'Алатский район', en: 'Olot District' },
      { code: 'BUX-PES', uz: 'Peshku tumani', ru: 'Пешкунский район', en: 'Peshku District' },
      { code: 'BUX-QOR', uz: "Qorakoʻl tumani", ru: 'Каракульский район', en: 'Qorakol District' },
      { code: 'BUX-QRV', uz: 'Qorovulbozor tumani', ru: 'Караулбазарский район', en: 'Qorovulbozor District' },
      { code: 'BUX-ROM', uz: 'Romitan tumani', ru: 'Ромитанский район', en: 'Romitan District' },
      { code: 'BUX-SHO', uz: 'Shofirkon tumani', ru: 'Шафирканский район', en: 'Shofirkon District' },
      { code: 'BUX-VOB', uz: 'Vobkent tumani', ru: 'Вабкентский район', en: 'Vobkent District' },
    ],
  },
  {
    code: 'FAR',
    uz: "Fargʻona viloyati",
    uzCyrl: 'Фарғона вилояти',
    ru: 'Ферганская область',
    en: 'Fergana Region',
    center: { lat: 40.3894, lng: 71.7833 },
    districts: [
      { code: 'FAR-FAR-C', uz: "Fargʻona shahri", ru: 'город Фергана', en: 'Fergana city', isCity: true, center: { lat: 40.3894, lng: 71.7833 } },
      { code: 'FAR-MAR-C', uz: "Margʻilon shahri", ru: 'город Маргилан', en: 'Margilan city', isCity: true, center: { lat: 40.4711, lng: 71.7244 } },
      { code: 'FAR-QOQ-C', uz: "Qoʻqon shahri", ru: 'город Коканд', en: 'Kokand city', isCity: true, center: { lat: 40.5286, lng: 70.9425 } },
      { code: 'FAR-QUV-C', uz: 'Quvasoy shahri', ru: 'город Кувасай', en: 'Quvasoy city', isCity: true },
      { code: 'FAR-BES', uz: 'Beshariq tumani', ru: 'Бешарыкский район', en: 'Beshariq District' },
      { code: 'FAR-BOG', uz: 'Bogʻdod tumani', ru: 'Багдадский район', en: 'Bog\u02bbdod District' },
      { code: 'FAR-BUV', uz: 'Buvayda tumani', ru: 'Бувайдинский район', en: 'Buvayda District' },
      { code: 'FAR-DAN', uz: "Dangʻara tumani", ru: 'Дангаринский район', en: 'Dang\u02bbara District' },
      { code: 'FAR-FAR', uz: "Fargʻona tumani", ru: 'Ферганский район', en: 'Fergana District' },
      { code: 'FAR-FUR', uz: 'Furqat tumani', ru: 'Фуркатский район', en: 'Furqat District' },
      { code: 'FAR-OLT', uz: 'Oltiariq tumani', ru: 'Алтыарыкский район', en: 'Oltiariq District' },
      { code: 'FAR-QOS', uz: "Qoʻshtepa tumani", ru: 'Куштепинский район', en: 'Qoshtepa District' },
      { code: 'FAR-QUV', uz: 'Quva tumani', ru: 'Кувинский район', en: 'Quva District' },
      { code: 'FAR-RIS', uz: 'Rishton tumani', ru: 'Риштанский район', en: 'Rishton District' },
      { code: 'FAR-SOX', uz: 'Soʻx tumani', ru: 'Сохский район', en: 'Sokh District' },
      { code: 'FAR-TOS', uz: 'Toshloq tumani', ru: 'Ташлакский район', en: 'Toshloq District' },
      { code: 'FAR-UCH', uz: "Uchkoʻprik tumani", ru: 'Учкуприкский район', en: 'Uchkoprik District' },
      { code: 'FAR-UZB', uz: 'Oʻzbekiston tumani', ru: 'Узбекистанский район', en: 'Uzbekistan District' },
      { code: 'FAR-YOZ', uz: 'Yozyovon tumani', ru: 'Язъяванский район', en: 'Yozyovon District' },
    ],
  },
  {
    code: 'JIZ',
    uz: 'Jizzax viloyati',
    uzCyrl: 'Жиззах вилояти',
    ru: 'Джизакская область',
    en: 'Jizzakh Region',
    center: { lat: 40.1158, lng: 67.8422 },
    districts: [
      { code: 'JIZ-JIZ-C', uz: 'Jizzax shahri', ru: 'город Джизак', en: 'Jizzakh city', isCity: true, center: { lat: 40.1158, lng: 67.8422 } },
      { code: 'JIZ-ARN', uz: 'Arnasoy tumani', ru: 'Арнасайский район', en: 'Arnasoy District' },
      { code: 'JIZ-BAX', uz: 'Baxmal tumani', ru: 'Бахмальский район', en: 'Baxmal District' },
      { code: 'JIZ-DOS', uz: "Doʻstlik tumani", ru: 'Дустликский район', en: 'Dostlik District' },
      { code: 'JIZ-FOR', uz: 'Forish tumani', ru: 'Фаришский район', en: 'Forish District' },
      { code: 'JIZ-GAL', uz: "Gʻallaorol tumani", ru: 'Галляаральский район', en: 'G\u02bballaorol District' },
      { code: 'JIZ-MIR', uz: "Mirzachoʻl tumani", ru: 'Мирзачульский район', en: 'Mirzacho\u02bbl District' },
      { code: 'JIZ-PAX', uz: 'Paxtakor tumani', ru: 'Пахтакорский район', en: 'Paxtakor District' },
      { code: 'JIZ-SHA', uz: 'Sharof Rashidov tumani', ru: 'район Шарафа Рашидова', en: 'Sharof Rashidov District' },
      { code: 'JIZ-YAN', uz: 'Yangiobod tumani', ru: 'Янгиабадский район', en: 'Yangiobod District' },
      { code: 'JIZ-ZAF', uz: 'Zafarobod tumani', ru: 'Зафарабадский район', en: 'Zafarobod District' },
      { code: 'JIZ-ZAR', uz: 'Zarbdor tumani', ru: 'Зарбдарский район', en: 'Zarbdor District' },
      { code: 'JIZ-ZOM', uz: 'Zomin tumani', ru: 'Зааминский район', en: 'Zomin District' },
    ],
  },
  {
    code: 'XOR',
    uz: 'Xorazm viloyati',
    uzCyrl: 'Хоразм вилояти',
    ru: 'Хорезмская область',
    en: 'Khorezm Region',
    center: { lat: 41.5506, lng: 60.6317 },
    districts: [
      { code: 'XOR-URG-C', uz: 'Urganch shahri', ru: 'город Ургенч', en: 'Urgench city', isCity: true, center: { lat: 41.5506, lng: 60.6317 } },
      { code: 'XOR-XIV-C', uz: 'Xiva shahri', ru: 'город Хива', en: 'Khiva city', isCity: true, center: { lat: 41.3775, lng: 60.3639 } },
      { code: 'XOR-BOG', uz: 'Bogʻot tumani', ru: 'Багатский район', en: 'Bog\u02bbot District' },
      { code: 'XOR-GUR', uz: 'Gurlan tumani', ru: 'Гурленский район', en: 'Gurlan District' },
      { code: 'XOR-HAZ', uz: 'Hazorasp tumani', ru: 'Хазараспский район', en: 'Hazorasp District' },
      { code: 'XOR-QOS', uz: "Qoʻshkoʻpir tumani", ru: 'Кошкупырский район', en: 'Qoshkopir District' },
      { code: 'XOR-SHO', uz: 'Shovot tumani', ru: 'Шаватский район', en: 'Shovot District' },
      { code: 'XOR-TUP', uz: "Tuproqqalʼa tumani", ru: 'Тупраккалинский район', en: 'Tuproqqala District' },
      { code: 'XOR-URG', uz: 'Urganch tumani', ru: 'Ургенчский район', en: 'Urgench District' },
      { code: 'XOR-XON', uz: 'Xonqa tumani', ru: 'Ханкинский район', en: 'Xonqa District' },
      { code: 'XOR-XIV', uz: 'Xiva tumani', ru: 'Хивинский район', en: 'Khiva District' },
      { code: 'XOR-YAA', uz: 'Yangiariq tumani', ru: 'Янгиарыкский район', en: 'Yangiariq District' },
      { code: 'XOR-YAB', uz: 'Yangibozor tumani', ru: 'Янгибазарский район', en: 'Yangibozor District' },
    ],
  },
  {
    code: 'NAM',
    uz: 'Namangan viloyati',
    uzCyrl: 'Наманган вилояти',
    ru: 'Наманганская область',
    en: 'Namangan Region',
    center: { lat: 40.9983, lng: 71.6726 },
    districts: [
      { code: 'NAM-NAM-C', uz: 'Namangan shahri', ru: 'город Наманган', en: 'Namangan city', isCity: true, center: { lat: 40.9983, lng: 71.6726 } },
      { code: 'NAM-CHO', uz: 'Chortoq tumani', ru: 'Чартакский район', en: 'Chortoq District' },
      { code: 'NAM-CHU', uz: 'Chust tumani', ru: 'Чустский район', en: 'Chust District' },
      { code: 'NAM-DAV', uz: 'Davlatobod tumani', ru: 'Давлатабадский район', en: 'Davlatobod District' },
      { code: 'NAM-KOS', uz: 'Kosonsoy tumani', ru: 'Касансайский район', en: 'Kosonsoy District' },
      { code: 'NAM-MIN', uz: 'Mingbuloq tumani', ru: 'Мингбулакский район', en: 'Mingbuloq District' },
      { code: 'NAM-NAM', uz: 'Namangan tumani', ru: 'Наманганский район', en: 'Namangan District' },
      { code: 'NAM-NOR', uz: 'Norin tumani', ru: 'Нарынский район', en: 'Norin District' },
      { code: 'NAM-POP', uz: 'Pop tumani', ru: 'Папский район', en: 'Pop District' },
      { code: 'NAM-TOR', uz: "Toʻraqoʻrgʻon tumani", ru: 'Туракурганский район', en: 'Toraqorgon District' },
      { code: 'NAM-UCH', uz: "Uchqoʻrgʻon tumani", ru: 'Учкурганский район', en: 'Uchqorgon District' },
      { code: 'NAM-UYC', uz: 'Uychi tumani', ru: 'Уйчинский район', en: 'Uychi District' },
      { code: 'NAM-YAN', uz: "Yangiqoʻrgʻon tumani", ru: 'Янгикурганский район', en: 'Yangiqorgon District' },
    ],
  },
  {
    code: 'NAV',
    uz: 'Navoiy viloyati',
    uzCyrl: 'Навоий вилояти',
    ru: 'Навоийская область',
    en: 'Navoiy Region',
    center: { lat: 40.0844, lng: 65.3792 },
    districts: [
      { code: 'NAV-NAV-C', uz: 'Navoiy shahri', ru: 'город Навои', en: 'Navoiy city', isCity: true, center: { lat: 40.0844, lng: 65.3792 } },
      { code: 'NAV-ZAR-C', uz: 'Zarafshon shahri', ru: 'город Зарафшан', en: 'Zarafshon city', isCity: true },
      { code: 'NAV-KAR', uz: 'Karmana tumani', ru: 'Карманинский район', en: 'Karmana District' },
      { code: 'NAV-KON', uz: 'Konimex tumani', ru: 'Канимехский район', en: 'Konimex District' },
      { code: 'NAV-NAB', uz: 'Navbahor tumani', ru: 'Навбахорский район', en: 'Navbahor District' },
      { code: 'NAV-NUR', uz: 'Nurota tumani', ru: 'Нуратинский район', en: 'Nurota District' },
      { code: 'NAV-QIZ', uz: 'Qiziltepa tumani', ru: 'Кызылтепинский район', en: 'Qiziltepa District' },
      { code: 'NAV-TOM', uz: 'Tomdi tumani', ru: 'Тамдынский район', en: 'Tomdi District' },
      { code: 'NAV-UCH', uz: 'Uchquduq tumani', ru: 'Учкудукский район', en: 'Uchquduq District' },
      { code: 'NAV-XAT', uz: 'Xatirchi tumani', ru: 'Хатырчинский район', en: 'Xatirchi District' },
    ],
  },
  {
    code: 'QAS',
    uz: 'Qashqadaryo viloyati',
    uzCyrl: 'Қашқадарё вилояти',
    ru: 'Кашкадарьинская область',
    en: 'Qashqadaryo Region',
    center: { lat: 38.8606, lng: 65.7847 },
    districts: [
      { code: 'QAS-QAR-C', uz: 'Qarshi shahri', ru: 'город Карши', en: 'Qarshi city', isCity: true, center: { lat: 38.8606, lng: 65.7847 } },
      { code: 'QAS-SHA-C', uz: 'Shahrisabz shahri', ru: 'город Шахрисабз', en: 'Shahrisabz city', isCity: true, center: { lat: 39.0578, lng: 66.8306 } },
      { code: 'QAS-CHI', uz: 'Chiroqchi tumani', ru: 'Чиракчинский район', en: 'Chiroqchi District' },
      { code: 'QAS-DEH', uz: 'Dehqonobod tumani', ru: 'Дехканабадский район', en: 'Dehqonobod District' },
      { code: 'QAS-GUZ', uz: "Gʻuzor tumani", ru: 'Гузарский район', en: 'G\u02bbuzor District' },
      { code: 'QAS-KAS', uz: 'Kasbi tumani', ru: 'Касбийский район', en: 'Kasbi District' },
      { code: 'QAS-KIT', uz: 'Kitob tumani', ru: 'Китабский район', en: 'Kitob District' },
      { code: 'QAS-KOS', uz: 'Koson tumani', ru: 'Касанский район', en: 'Koson District' },
      { code: 'QAS-KOK', uz: 'Koʻkdala tumani', ru: 'Кукдалинский район', en: 'Kokdala District' },
      { code: 'QAS-MIR', uz: 'Mirishkor tumani', ru: 'Миришкорский район', en: 'Mirishkor District' },
      { code: 'QAS-MUB', uz: 'Muborak tumani', ru: 'Мубарекский район', en: 'Muborak District' },
      { code: 'QAS-NIS', uz: 'Nishon tumani', ru: 'Нишанский район', en: 'Nishon District' },
      { code: 'QAS-QAM', uz: 'Qamashi tumani', ru: 'Камашинский район', en: 'Qamashi District' },
      { code: 'QAS-QAR', uz: 'Qarshi tumani', ru: 'Каршинский район', en: 'Qarshi District' },
      { code: 'QAS-SHA', uz: 'Shahrisabz tumani', ru: 'Шахрисабзский район', en: 'Shahrisabz District' },
      { code: 'QAS-YAK', uz: "Yakkabogʻ tumani", ru: 'Яккабагский район', en: 'Yakkabog\u02bb District' },
    ],
  },
  {
    code: 'SAM',
    uz: 'Samarqand viloyati',
    uzCyrl: 'Самарқанд вилояти',
    ru: 'Самаркандская область',
    en: 'Samarkand Region',
    center: { lat: 39.6542, lng: 66.9597 },
    districts: [
      { code: 'SAM-SAM-C', uz: 'Samarqand shahri', ru: 'город Самарканд', en: 'Samarkand city', isCity: true, center: { lat: 39.6542, lng: 66.9597 } },
      { code: 'SAM-KAT-C', uz: "Kattaqoʻrgʻon shahri", ru: 'город Каттакурган', en: 'Kattaqorgon city', isCity: true },
      { code: 'SAM-BUL', uz: "Bulungʻur tumani", ru: 'Булунгурский район', en: 'Bulung\u02bbur District' },
      { code: 'SAM-ISH', uz: 'Ishtixon tumani', ru: 'Иштыханский район', en: 'Ishtixon District' },
      { code: 'SAM-JOM', uz: 'Jomboy tumani', ru: 'Джамбайский район', en: 'Jomboy District' },
      { code: 'SAM-KAT', uz: "Kattaqoʻrgʻon tumani", ru: 'Каттакурганский район', en: 'Kattaqorgon District' },
      { code: 'SAM-NAR', uz: 'Narpay tumani', ru: 'Нарпайский район', en: 'Narpay District' },
      { code: 'SAM-NUR', uz: 'Nurobod tumani', ru: 'Нурабадский район', en: 'Nurobod District' },
      { code: 'SAM-OQD', uz: 'Oqdaryo tumani', ru: 'Акдарьинский район', en: 'Oqdaryo District' },
      { code: 'SAM-PAS', uz: "Pastdargʻom tumani", ru: 'Пастдаргомский район', en: 'Pastdarg\u02bbom District' },
      { code: 'SAM-PAX', uz: 'Paxtachi tumani', ru: 'Пахтачийский район', en: 'Paxtachi District' },
      { code: 'SAM-PAY', uz: 'Payariq tumani', ru: 'Пайарыкский район', en: 'Payariq District' },
      { code: 'SAM-QOS', uz: 'Qoʻshrabot tumani', ru: 'Кошрабадский район', en: 'Qoshrabot District' },
      { code: 'SAM-SAM', uz: 'Samarqand tumani', ru: 'Самаркандский район', en: 'Samarkand District' },
      { code: 'SAM-TOY', uz: 'Toyloq tumani', ru: 'Тайлякский район', en: 'Toyloq District' },
      { code: 'SAM-URG', uz: 'Urgut tumani', ru: 'Ургутский район', en: 'Urgut District' },
    ],
  },
  {
    code: 'SIR',
    uz: 'Sirdaryo viloyati',
    uzCyrl: 'Сирдарё вилояти',
    ru: 'Сырдарьинская область',
    en: 'Sirdaryo Region',
    center: { lat: 40.4897, lng: 68.7842 },
    districts: [
      { code: 'SIR-GUL-C', uz: 'Guliston shahri', ru: 'город Гулистан', en: 'Gulistan city', isCity: true, center: { lat: 40.4897, lng: 68.7842 } },
      { code: 'SIR-SHI-C', uz: 'Shirin shahri', ru: 'город Ширин', en: 'Shirin city', isCity: true },
      { code: 'SIR-YAN-C', uz: 'Yangiyer shahri', ru: 'город Янгиер', en: 'Yangiyer city', isCity: true },
      { code: 'SIR-BOY', uz: 'Boyovut tumani', ru: 'Баяутский район', en: 'Boyovut District' },
      { code: 'SIR-GUL', uz: 'Guliston tumani', ru: 'Гулистанский район', en: 'Gulistan District' },
      { code: 'SIR-MIR', uz: 'Mirzaobod tumani', ru: 'Мирзаабадский район', en: 'Mirzaobod District' },
      { code: 'SIR-OQO', uz: 'Oqoltin tumani', ru: 'Акалтынский район', en: 'Oqoltin District' },
      { code: 'SIR-SAR', uz: 'Sardoba tumani', ru: 'Сардобинский район', en: 'Sardoba District' },
      { code: 'SIR-SAY', uz: 'Sayxunobod tumani', ru: 'Сайхунабадский район', en: 'Sayxunobod District' },
      { code: 'SIR-SIR', uz: 'Sirdaryo tumani', ru: 'Сырдарьинский район', en: 'Sirdaryo District' },
      { code: 'SIR-XOV', uz: 'Xovos tumani', ru: 'Хавастский район', en: 'Xovos District' },
    ],
  },
  {
    code: 'SUR',
    uz: 'Surxondaryo viloyati',
    uzCyrl: 'Сурхондарё вилояти',
    ru: 'Сурхандарьинская область',
    en: 'Surxondaryo Region',
    center: { lat: 37.2242, lng: 67.2783 },
    districts: [
      { code: 'SUR-TER-C', uz: 'Termiz shahri', ru: 'город Термез', en: 'Termez city', isCity: true, center: { lat: 37.2242, lng: 67.2783 } },
      { code: 'SUR-ANG', uz: 'Angor tumani', ru: 'Ангорский район', en: 'Angor District' },
      { code: 'SUR-BAN', uz: 'Bandixon tumani', ru: 'Бандиханский район', en: 'Bandixon District' },
      { code: 'SUR-BOY', uz: 'Boysun tumani', ru: 'Байсунский район', en: 'Boysun District' },
      { code: 'SUR-DEN', uz: 'Denov tumani', ru: 'Денауский район', en: 'Denov District' },
      { code: 'SUR-JAR', uz: "Jarqoʻrgʻon tumani", ru: 'Джаркурганский район', en: 'Jarqorgon District' },
      { code: 'SUR-MUZ', uz: 'Muzrabot tumani', ru: 'Музрабадский район', en: 'Muzrabot District' },
      { code: 'SUR-OLT', uz: 'Oltinsoy tumani', ru: 'Алтынсайский район', en: 'Oltinsoy District' },
      { code: 'SUR-QIZ', uz: 'Qiziriq tumani', ru: 'Кызырыкский район', en: 'Qiziriq District' },
      { code: 'SUR-QUM', uz: "Qumqoʻrgʻon tumani", ru: 'Кумкурганский район', en: 'Qumqorgon District' },
      { code: 'SUR-SAR', uz: 'Sariosiyo tumani', ru: 'Сариасийский район', en: 'Sariosiyo District' },
      { code: 'SUR-SHE', uz: 'Sherobod tumani', ru: 'Шерабадский район', en: 'Sherobod District' },
      { code: 'SUR-SHO', uz: "Shoʻrchi tumani", ru: 'Шурчинский район', en: 'Shorchi District' },
      { code: 'SUR-TER', uz: 'Termiz tumani', ru: 'Термезский район', en: 'Termez District' },
      { code: 'SUR-UZU', uz: 'Uzun tumani', ru: 'Узунский район', en: 'Uzun District' },
    ],
  },
  {
    code: 'TOS',
    uz: 'Toshkent viloyati',
    uzCyrl: 'Тошкент вилояти',
    ru: 'Ташкентская область',
    en: 'Tashkent Region',
    center: { lat: 41.0333, lng: 69.3167 },
    districts: [
      { code: 'TOS-NUR-C', uz: 'Nurafshon shahri', ru: 'город Нурафшан', en: 'Nurafshon city', isCity: true },
      { code: 'TOS-ANG-C', uz: 'Angren shahri', ru: 'город Ангрен', en: 'Angren city', isCity: true },
      { code: 'TOS-BEK-C', uz: 'Bekobod shahri', ru: 'город Бекабад', en: 'Bekobod city', isCity: true },
      { code: 'TOS-CHI-C', uz: 'Chirchiq shahri', ru: 'город Чирчик', en: 'Chirchiq city', isCity: true, center: { lat: 41.4689, lng: 69.5822 } },
      { code: 'TOS-OLM-C', uz: 'Olmaliq shahri', ru: 'город Алмалык', en: 'Olmaliq city', isCity: true },
      { code: 'TOS-OHA-C', uz: 'Ohangaron shahri', ru: 'город Ахангаран', en: 'Ohangaron city', isCity: true },
      { code: 'TOS-YAN-C', uz: "Yangiyoʻl shahri", ru: 'город Янгиюль', en: 'Yangiyol city', isCity: true },
      { code: 'TOS-BEK', uz: 'Bekobod tumani', ru: 'Бекабадский район', en: 'Bekobod District' },
      { code: 'TOS-BOK', uz: "Boʻka tumani", ru: 'Букинский район', en: 'Boka District' },
      { code: 'TOS-BOS', uz: "Boʻstonliq tumani", ru: 'Бостанлыкский район', en: 'Bostanliq District' },
      { code: 'TOS-CHI', uz: 'Chinoz tumani', ru: 'Чиназский район', en: 'Chinoz District' },
      { code: 'TOS-OHA', uz: 'Ohangaron tumani', ru: 'Ахангаранский район', en: 'Ohangaron District' },
      { code: 'TOS-OQQ', uz: "Oqqoʻrgʻon tumani", ru: 'Аккурганский район', en: 'Oqqorgon District' },
      { code: 'TOS-ORT', uz: 'Oʻrtachirchiq tumani', ru: 'Уртачирчикский район', en: 'Ortachirchiq District' },
      { code: 'TOS-PAR', uz: 'Parkent tumani', ru: 'Паркентский район', en: 'Parkent District' },
      { code: 'TOS-PIS', uz: 'Piskent tumani', ru: 'Пскентский район', en: 'Piskent District' },
      { code: 'TOS-QIB', uz: 'Qibray tumani', ru: 'Кибрайский район', en: 'Qibray District' },
      { code: 'TOS-QUY', uz: 'Quyichirchiq tumani', ru: 'Куйичирчикский район', en: 'Quyichirchiq District' },
      { code: 'TOS-TOS', uz: 'Toshkent tumani', ru: 'Ташкентский район', en: 'Tashkent District' },
      { code: 'TOS-YAN', uz: "Yangiyoʻl tumani", ru: 'Янгиюльский район', en: 'Yangiyol District' },
      { code: 'TOS-YUQ', uz: 'Yuqorichirchiq tumani', ru: 'Юкоричирчикский район', en: 'Yuqorichirchiq District' },
      { code: 'TOS-ZAN', uz: 'Zangiota tumani', ru: 'Зангиатинский район', en: 'Zangiota District' },
    ],
  },
  {
    code: 'TSH',
    uz: 'Toshkent shahri',
    uzCyrl: 'Тошкент шаҳри',
    ru: 'город Ташкент',
    en: 'Tashkent City',
    center: { lat: 41.2995, lng: 69.2401 },
    districts: [
      { code: 'TSH-BEK', uz: 'Bektemir tumani', ru: 'Бектемирский район', en: 'Bektemir District', center: { lat: 41.2172, lng: 69.3339 } },
      { code: 'TSH-CHI', uz: 'Chilonzor tumani', ru: 'Чиланзарский район', en: 'Chilanzar District', center: { lat: 41.2756, lng: 69.2044 } },
      { code: 'TSH-MIR', uz: 'Mirobod tumani', ru: 'Мирабадский район', en: 'Mirobod District', center: { lat: 41.2853, lng: 69.2814 } },
      { code: 'TSH-MIU', uz: "Mirzo Ulugʻbek tumani", ru: 'Мирзо-Улугбекский район', en: 'Mirzo Ulugbek District', center: { lat: 41.3253, lng: 69.3350 } },
      { code: 'TSH-OLM', uz: 'Olmazor tumani', ru: 'Алмазарский район', en: 'Olmazor District', center: { lat: 41.3475, lng: 69.2036 } },
      { code: 'TSH-SER', uz: 'Sergeli tumani', ru: 'Сергелийский район', en: 'Sergeli District', center: { lat: 41.2233, lng: 69.2200 } },
      { code: 'TSH-SHA', uz: 'Shayxontohur tumani', ru: 'Шайхантахурский район', en: 'Shayxontohur District', center: { lat: 41.3175, lng: 69.2325 } },
      { code: 'TSH-UCH', uz: 'Uchtepa tumani', ru: 'Учтепинский район', en: 'Uchtepa District', center: { lat: 41.2894, lng: 69.1683 } },
      { code: 'TSH-YAK', uz: 'Yakkasaroy tumani', ru: 'Яккасарайский район', en: 'Yakkasaroy District', center: { lat: 41.2831, lng: 69.2456 } },
      { code: 'TSH-YAS', uz: 'Yashnobod tumani', ru: 'Яшнабадский район', en: 'Yashnobod District', center: { lat: 41.2833, lng: 69.3333 } },
      { code: 'TSH-YUN', uz: 'Yunusobod tumani', ru: 'Юнусабадский район', en: 'Yunusobod District', center: { lat: 41.3639, lng: 69.2867 } },
      { code: 'TSH-YAH', uz: 'Yangihayot tumani', ru: 'Янгихаётский район', en: 'Yangihayot District', center: { lat: 41.2064, lng: 69.2483 } },
    ],
  },
];

export const SEED_REGION_COUNT = SEED_REGIONS.length;
export const SEED_DISTRICT_COUNT = SEED_REGIONS.reduce(
  (total, region) => total + region.districts.length,
  0,
);
